image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose~=1.23.0

stages:
  - build

deploy:
  stage: build
  #only:
  #  - production # только для этой ветки
  script:
    - docker-compose up -d --build
  #environment:
      #name: production
  when: on_success
  #except:
  #  - master # исключить ветки
  tags:
    - docker