stages:
  - build

deploy:
  stage: build
  #only:
  #  - production # только для этой ветки
  script:
    - docker-compose stop
    - docker-compose up -d --build
    - npm i
    - npm start
  when: always
  #except:
  #  - master # исключить ветки
  tags:
    - docker