image: docker

services:
  - docker:dind

before_script:
  - apk add --update py-pip &&
    pip install docker-compose

stages:
  - build

build:
  stage: build
  #only:
  #  - production
  script:
    - sudo apt-get install -y gcc -y
    - sudo apt-get install -y python-pip
  when: manual
  #except:
  #  - master

build1:
  stage: deploy
  #only:
  #  - production
  script:
    - pip install docker-compose
    - docker-compose up -d build
  environment: production
  when: manual
  #except:
  #  - master