image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose~=1.23.0

stages:
  - build

build1:
  stage: build
  #only:
  #  - production
  script:
    - docker-compose up -d build
  environment: production
  when: on_success
  #except:
  #  - master