image: docker

services:
  - docker:dind

before_script:
  - apk add --update py-pip &&
    pip install gcc &&
    pip install docker-compose

stages:
  - build

build1:
  stage: build
  #only:
  #  - production
  script:
    - docker-compose up -d build
  environment: production
  when: on_success
  #except:
  #  - master