image: docker

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  #only:
  #  - production
  script:
    - apt-get install -y python-pip
    - pip install docker-compose
  #except:
  #  - master

build1:
  stage: deploy
  #only:
  #  - production
  script:
    - docker-compose up -d build
  environment: production
  when: on_success
  #except:
  #  - master