image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose~=1.23.0

stages:
  - build
  - deploy

build:
  stage: build
  #only:
  #  - production # только для этой ветки
  script:
    - docker-compose build
  environment:
    name: production
  #except:
  #  - master # исключить ветки
  tags:
    - docker

deploy:
  stage: deploy
  #only:
  #  - production # только для этой ветки
  script:
    - docker-compose up -d
  environment:
    name: production
  when: on_success
  #except:
  #  - master # исключить ветки
  tags:
    - docker