version: "2"
services:
  rate:
    container_name: rate
    restart: always
    depends_on:
      - mongo-rate
      - hub
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    links:
      - mongo-rate
      - hub

  mongo-rate:
    container_name: mongo-rate
    restart: always
    image: mongo
    volumes:
      - ./docker/mongo-seed/db:/data/db
    ports:
      - "27017:27017"

  mongo-rate-seed:
    container_name: mongo-rate-seed
    depends_on:
      - mongo-rate
    build:
      context: .
      dockerfile: docker/mongo-seed/Dockerfile
    links:
      - mongo-rate

  chrome:
    container_name: chrome
    restart: always
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    container_name: hub
    restart: always
    image: selenium/hub:3.14.0-gallium
    environment:
      - GRID_BROWSER_TIMEOUT=3400
      - GRID_TIMEOUT=3600
    ports:
      - "4444:4444"