version: "2"
services:
  mongo-rate:
    container_name: mongo-rate
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - bot

  mongo-rate-seed:
    container_name: mongo-rate-seed
    build:
      context: .
      dockerfile: docker/mongo-seed/Dockerfile
    links:
      - mongo-rate
    networks:
      - bot

#  rate:
#    container_name: rate
#    build:
#      context: .
#      dockerfile: docker/node/Dockerfile
#    links:
#      - mongo-rate
#    networks:
#      - bot

networks:
  bot: